ALTER TABLE channels ADD COLUMN rpm_limit INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE channels ADD COLUMN max_inflight INTEGER NOT NULL DEFAULT 32;

ALTER TABLE channels ADD COLUMN safety_factor REAL NOT NULL DEFAULT 0.9;

ALTER TABLE channels ADD COLUMN enabled_for_async INTEGER NOT NULL DEFAULT 1;

ALTER TABLE channels ADD COLUMN dispatch_weight INTEGER NOT NULL DEFAULT 100;
